---
- name: Run lspci command and save output
  ansible.builtin.command: lspci -nn
  register: lspci_output
  changed_when: false

- name: Init presense facts for {{ gpu_validation_vendor_name }}
  ansible.builtin.set_fact:
    gpu_validation_found: "{{ gpu_validation_found | default({}) | combine({ gpu_validation_vendor_name: false }) }}"

- name: Set presence facts for {{ gpu_validation_vendor_name }}
  ansible.builtin.set_fact:
    gpu_validation_found: "{{ gpu_validation_found | default({}) | combine({ gpu_validation_vendor_name: true }) }}"
  when: lspci_output.stdout is search(gpu_validation_vendor_name, ignorecase=true)

- name: Assrt that found PCI devices for vendor name {{ gpu_validation_vendor_name }}
  ansible.builtin.assert:
    that: gpu_validation_found[gpu_validation_vendor_name] | bool
    fail_msg: "No {{ gpu_validation_vendor_name }} GPUs found"
