---
- name: Set DNS server using nmcli if gpu_validation_dns_server is set
  ansible.builtin.shell: |
    nmcli con mod "System eth0" ipv4.dns "{{ gpu_validation_dns_server }}" ipv4.ignore-auto-dns yes
    nmcli con up "System eth0"
  when: gpu_validation_dns_server != ""
  changed_when: true

- name: Configure proxy settings
  ansible.builtin.include_tasks: proxy.yaml
  when: (gpu_validation_http_proxy | length > 0) or (gpu_validation_https_proxy | length > 0)

- name: Install needed driver dependency packages
  when:
    - gpu_validation_mode in ["mig", "vgpu"]
  block:
    - name: Execute bootstrap command
      ansible.builtin.include_role:
        name: osp.edpm.edpm_bootstrap
        tasks_from: bootstrap_command.yml

    - name: Add EPEL repository for DKMS (UNSUPPORTED)
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: "https://download.fedoraproject.org/pub/epel/{{ ansible_facts['distribution_major_version'] }}/Everything/$basearch/"
        enabled: 1
        gpgcheck: 1
        gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_facts['distribution_major_version'] }}"

    - name: Get running kernel version
      ansible.builtin.command: uname -r
      register: running_kernel
      changed_when: false

    - name: Install DKMS and kernel-devel for running kernel (UNSUPPORTED)
      ansible.builtin.dnf:
        name:
          - dkms
          - "kernel-devel-{{ running_kernel.stdout }}"
          - "kernel-headers-{{ running_kernel.stdout }}"
        state: present

- name: Install pciutils package
  ansible.builtin.dnf:
    name: pciutils
    state: present

- name: Install pip package
  ansible.builtin.dnf:
    name: python-pip
    state: present

- name: Install podman package
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Copy scripts from local to RHEL AI machine
  ansible.builtin.copy:
    src: "{{ role_path }}/files/scripts"
    dest: /tmp
    mode: "1777"
